version: "3.9"

services:

  neo4j-db:
    image: neo4j:5.17.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - data:/data

volumes:
  data:
