version: "3.9"

services:

  neo4j-db:
    image: neo4j:5.17.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data

  psql-db:
    image: postgres:15.6
    ports:
      - "5492:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  neo4j-data:
  psql-data:
