spring:
  application:
    name: test-neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5492/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true